#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  next:"
  echo " todo.sh next"
  echo " if todo.txt is an outline with"
  echo " tabbed indentations, next " 
  echo " displays tasks with no tasks or "
  echo " higher siblings actions "
  exit
}

TOTAL=$( sed -n '$ =' "$TODO_FILE" )
PADDING=${#TOTAL}

awk 'BEGIN {
    FS = "\t";
    main = 1
    prevleaf = 1
    curr=0
    } ;
    {
    prev=curr
    prevLine=currLine
    curr=NF
    currLine=$curr
    # identify prevleaf
    if (prev >= curr){
      prevleaf=1
    }
    else
    {prevleaf=0}

    if (prevleaf && main)
      {prevnext=1}
    else
      {prevnext=0}
    if( prevnext == 1)
      {
        print prevLine
      }
    else
      {
        print ""
      }
 

    # if prev is prevleaf, curr is off main trunk
    if (prevleaf > 0){
      main =0
    }

    # new root means back on main
    if (curr==1){
      main=1
    }

}
END {
  if ((main==1 && curr > prev) || curr==1)
    print currLine
 }'  $TODO_FILE  | TODOTXT_VERBOSE=0 _format '' "$PADDING" "$@" # use _format to highlight
