#!/bin/bash
# nextin

mkdir -p next #make next dir if not there already

sed -i  '/^\s*$/d' $TODO_DIR/next/todo.txt #trim any blank lines

#loop through /next/todo
LINES=$(wc -l $TODO_DIR/next/todo.txt | awk '{print $1}')
 for ((i=1; i <= LINES+1; i++ ))
    do
    	# do done tasks from next/todo
       	taskDone=$(sed -ne ${i}p $TODO_DIR/next/todo.txt| grep -cE "x [0-9]{4}\-[0-9]{2}\-[0-9]")
    	if [ $taskDone -eq 1 ]
    		then
    		pattern=$(head -$i $TODO_DIR/next/todo.txt | tail -1| sed -e "s/^x [0-9]\{4\}\-[0-9]\{2\}\-[0-9]\{2\} //" | head -1)
    		todoLine=$(grep -Fn "$pattern" $TODO_FILE | grep -Eo 1 '[0-9]*' | head -1)
    		todo.sh 'do' $todoLine
    	else
    		# put any new tasks into todo.txt
			pattern=$(head -$i $TODO_DIR/next/todo.txt | tail -1) 
    		todoLine=$(grep -Fn "$pattern" $TODO_FILE |  sed 's/:.*//' ) 
    		if [ -z $todoLine ]
    			then
    			echo "$pattern" >> $TODO_FILE
    		fi
    	fi    	
    done

> $TODO_DIR/next/todo.txt

sed -i  '/^\s*$/d' $TODO_FILE